# Generated by Django 6.0.7 on 2026-08-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='apagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='desconto',
            field=models.BooleanField(default=False),
        ),
    ]
